#include "precompiled.hpp"
#include "c1/c1_globals.hpp"

C1_FLAGS(MATERIALIZE_DEVELOPER_FLAG, \
         MATERIALIZE_PD_DEVELOPER_FLAG, \
         MATERIALIZE_PRODUCT_FLAG, \
         MATERIALIZE_PD_PRODUCT_FLAG, \
         MATERIALIZE_DIAGNOSTIC_FLAG, \
         MATERIALIZE_PD_DIAGNOSTIC_FLAG, \
         MATERIALIZE_NOTPRODUCT_FLAG, \
         IGNORE_RANGE, \
         IGNORE_CONSTRAINT, \
         IGNORE_WRITEABLE)
